# Generated by Django 2.2.3 on 2019-07-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('axis_left', models.FloatField(default=0.0)),
                ('axis_top', models.FloatField(default=0.0)),
                ('product_image', models.TextField()),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('author_profile', models.TextField(blank=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('scrap_count', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='community.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created', models.CharField(max_length=20)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.Photo')),
            ],
        ),
    ]
