# Generated by Django 2.2.3 on 2019-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20190730_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='author_profile',
            new_name='author_profile_comment',
        ),
        migrations.AddField(
            model_name='photo',
            name='author_profile_image',
            field=models.TextField(blank=True),
        ),
    ]
