# Generated by Django 2.2.3 on 2019-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_photocomment_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
