# Generated by Django 2.2.3 on 2019-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20190730_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
