# Generated by Django 2.2.3 on 2019-07-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_photo_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Housewarming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('author_profile', models.TextField(blank=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('scrap_count', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('cover_image', models.TextField()),
                ('structure', models.CharField(max_length=20)),
                ('floor_space', models.CharField(max_length=10)),
                ('style', models.CharField(max_length=10)),
                ('work', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('family', models.CharField(max_length=10)),
                ('detail_part', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('comment_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HousewarmingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('author_profile_image', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('created', models.CharField(max_length=20)),
                ('housewarming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.Housewarming')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
