# Generated by Django 2.2.3 on 2019-07-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_detailcontent_housewarming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcontent',
            name='housewarming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_contents', to='community.Housewarming'),
        ),
    ]
