# Generated by Django 2.2.3 on 2019-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20190731_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housewarming',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='created',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='family',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='floor_space',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='structure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='style',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='housewarming',
            name='work',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarmingcomment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='housewarmingcomment',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='created',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
