# Generated by Django 2.2.3 on 2019-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('kakao', '카카오'), ('google', '구글'), ('naver', '네이버')], default='django', max_length=12, verbose_name='유형'),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
