# Generated by Django 2.2.3 on 2019-07-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190715_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='image',
            field=models.ImageField(blank=True, upload_to='store/category/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product_detail_images',
            name='pd_detail_image',
            field=models.ImageField(blank=True, upload_to='store/detail/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product_thumnail',
            name='pd_image',
            field=models.ImageField(blank=True, upload_to='store/thumnail/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_standard',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rv_image',
            field=models.ImageField(blank=True, upload_to='store/review/%Y/%m/%d'),
        ),
    ]
