# Generated by Django 2.2.3 on 2019-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190716_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail_images',
            name='pd_detail_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_thumnail',
            name='pd_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='deliver',
            field=models.CharField(default='일반택배배송', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='deliver_no_go',
            field=models.CharField(default='배송불가 지역이 없습니다.', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rv_image',
            field=models.TextField(),
        ),
    ]
