# Generated by Django 2.2.3 on 2019-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190716_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail_auth',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_component',
            field=models.TextField(max_length=45),
        ),
    ]
