# Generated by Django 2.2.3 on 2019-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190716_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_auth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_component',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail_size',
            field=models.CharField(max_length=200),
        ),
    ]
