# Generated by Django 2.2.3 on 2019-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190716_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pd_question',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product_detail_images',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product_options',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product_thumnail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pd_delivery',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pd_design',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pd_durability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pd_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
