# Generated by Django 2.2.3 on 2019-07-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190717_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_thumnail',
            new_name='ProductThumnail',
        ),
    ]
