# Generated by Django 2.2.3 on 2019-07-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190717_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_options',
            new_name='ProductOption',
        ),
    ]
