# Generated by Django 2.2.3 on 2019-07-17 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20190717_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDQnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('a_author', models.CharField(max_length=20)),
                ('a_comment', models.TextField(blank=True, null=True)),
                ('a_created', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pd_question',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pd_question',
            name='user',
        ),
        migrations.RenameField(
            model_name='productdetailimage',
            old_name='pd_detail_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='option_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='option_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productthumnail',
            old_name='pd_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rv_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pd_delivery',
            new_name='score_delivery',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pd_design',
            new_name='score_design',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pd_durability',
            new_name='score_durability',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pd_price',
            new_name='score_price',
        ),
        migrations.DeleteModel(
            name='PD_Answer',
        ),
        migrations.DeleteModel(
            name='PD_Question',
        ),
    ]
