# Generated by Django 2.2.3 on 2019-07-18 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190717_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score_delivery',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_design',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_durability',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_price',
        ),
        migrations.AddField(
            model_name='review',
            name='star_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, null=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/review/%Y/%m/%d'),
        ),
    ]
