# Generated by Django 2.2.3 on 2019-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_hotdealnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdealnumber',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
