# Generated by Django 2.2.3 on 2019-07-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20190723_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotDealNumber',
        ),
    ]
