# Generated by Django 2.2.3 on 2019-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_hotdealnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rnd_number', models.PositiveIntegerField(default=0)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
