# Generated by Django 2.2.3 on 2019-07-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190726_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orderer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orderer_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='orderer_phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rec_address1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rec_address2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rec_comment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rec_phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rec_zipcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient',
        ),
    ]
