# Generated by Django 2.2.3 on 2019-07-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_cronlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='direct_payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_option',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productordercart',
            name='product_option',
        ),
        migrations.RemoveField(
            model_name='productordercart',
            name='user',
        ),
        migrations.DeleteModel(
            name='DirectPayment',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProductOrderCart',
        ),
    ]
