# Generated by Django 2.2.3 on 2019-07-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20190731_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful',
        ),
    ]
